--- 
clone: 
  depth: 1
kind: pipeline
name: ZyCPipeline
concurrency:
  limit: 6
steps: 
  - 
    commands: 
      - "bash ./main.sh"
      - "bash ./umi-aosp-qk.sh"
    environment: 
      BOT_TOKEN: 
        from_secret: BOT_API_KEY
    image: fadlyas/kernel_dockerfile:latest
    name: ZyC-Build
    trigger: 
      branch: 
        - master
